/**
 * @fileoverview Filmography headings for every TMDb department and job.
 */

const PHRASE_BY_PROFESSION: Record<string, string> = {
  '"A" Camera Operator': 'shot by',
  '"B" Camera Operator': 'shot by',
  '"C" Camera Operator': 'shot by',
  '"D" Camera Operator': 'shot by',
  '24 Frame Playback': 'with visual effects by',
  '2D Artist': 'with visual effects by',
  '2D Sequence Supervisor': 'with visual effects by',
  '2D Supervisor': 'with visual effects by',
  '3D Animator': 'with visual effects by',
  '3D Artist': 'with visual effects by',
  '3D Coordinator': 'with visual effects by',
  '3D Digital Colorist': 'edited by',
  '3D Director': 'with visual effects by',
  '3D Editor': 'edited by',
  '3D Generalist': 'with visual effects by',
  '3D Modeller': 'with visual effects by',
  '3D Sequence Supervisor': 'with visual effects by',
  '3D Supervisor': 'with visual effects by',
  '3D Tracking Layout': 'with visual effects by',
  'ADR & Dubbing': 'with sound by',
  'ADR Coordinator': 'with sound by',
  'ADR Editor': 'with sound by',
  'ADR Engineer': 'with sound by',
  'ADR Mixer': 'with sound by',
  'ADR Post Producer': 'with sound by',
  'ADR Recording Engineer': 'with sound by',
  'ADR Recordist': 'with sound by',
  'ADR Supervisor': 'with sound by',
  'ADR Voice Casting': 'produced by',
  'Accountant': 'produced by',
  'Accounting Clerk Assistant': 'produced by',
  'Accounting Supervisor': 'produced by',
  'Accounting Trainee': 'produced by',
  'Acting': 'starring',
  'Acting Double': 'crew',
  'Action Director': 'directed by',
  'Actor': 'starring',
  'Actor\'s Assistant': 'crew',
  'Actors': 'starring',
  'Adaptation': 'written by',
  'Additional Camera': 'shot by',
  'Additional Casting': 'produced by',
  'Additional Colorist': 'edited by',
  'Additional Construction': 'designed by',
  'Additional Construction Grip': 'designed by',
  'Additional Dialogue': 'crew',
  'Additional Director of Photography': 'shot by',
  'Additional Editing': 'edited by',
  'Additional Editor': 'edited by',
  'Additional Editorial Assistant': 'edited by',
  'Additional Effects Development': 'with visual effects by',
  'Additional First Assistant Camera': 'shot by',
  'Additional Gaffer': 'lit by',
  'Additional Grip': 'shot by',
  'Additional Hairstylist': 'with costumes and makeup by',
  'Additional Key Construction Grip': 'designed by',
  'Additional Key Grip': 'shot by',
  'Additional Lighting Technician': 'lit by',
  'Additional Music': 'crew',
  'Additional Music Supervisor': 'with sound by',
  'Additional Photography': 'shot by',
  'Additional Post-Production Supervisor': 'produced by',
  'Additional Production Assistant': 'produced by',
  'Additional Production Sound Mixer': 'with sound by',
  'Additional Script Supervisor': 'crew',
  'Additional Second Assistant Camera': 'shot by',
  'Additional Second Assistant Director': 'directed by',
  'Additional Set Dresser': 'designed by',
  'Additional Set Photographer': 'shot by',
  'Additional Sound Re-Recording Mixer': 'with sound by',
  'Additional Sound Re-Recordist': 'with sound by',
  'Additional Soundtrack': 'with sound by',
  'Additional Still Photographer': 'shot by',
  'Additional Storyboarding': 'designed by',
  'Additional Third Assistant Director': 'directed by',
  'Additional Underwater Photography': 'shot by',
  'Additional Visual Effects': 'with visual effects by',
  'Additional Wardrobe Assistant': 'with costumes and makeup by',
  'Additional Writing': 'crew',
  'Administration': 'produced by',
  'Administrative Assistant': 'crew',
  'Aerial Camera': 'shot by',
  'Aerial Camera Technician': 'shot by',
  'Aerial Coordinator': 'crew',
  'Aerial Director of Photography': 'shot by',
  'Ager/Dyer': 'with costumes and makeup by',
  'Animal Coordinator': 'crew',
  'Animal Wrangler': 'crew',
  'Animation': 'with visual effects by',
  'Animation Coordinator': 'with visual effects by',
  'Animation Department Coordinator': 'with visual effects by',
  'Animation Director': 'with visual effects by',
  'Animation Fix Coordinator': 'with visual effects by',
  'Animation Manager': 'with visual effects by',
  'Animation Production Assistant': 'with visual effects by',
  'Animation Supervisor': 'with visual effects by',
  'Animation Technical Director': 'with visual effects by',
  'Animatronic and Prosthetic Effects': 'crew',
  'Animatronics Designer': 'crew',
  'Animatronics Supervisor': 'crew',
  'Apprentice Sound Editor': 'with sound by',
  'Archival Footage Coordinator': 'edited by',
  'Archival Footage Research': 'edited by',
  'Armorer': 'crew',
  'Armory Coordinator': 'crew',
  'Art': 'designed by',
  'Art Department Assistant': 'designed by',
  'Art Department Coordinator': 'designed by',
  'Art Department Manager': 'designed by',
  'Art Department Production Assistant': 'produced by',
  'Art Department Trainee': 'designed by',
  'Art Designer': 'designed by',
  'Art Direction': 'designed by',
  'Art Direction Intern': 'designed by',
  'Assistant Accountant': 'produced by',
  'Assistant Art Director': 'designed by',
  'Assistant Camera': 'shot by',
  'Assistant Chef': 'crew',
  'Assistant Chief Lighting Technician': 'lit by',
  'Assistant Costume Designer': 'with costumes and makeup by',
  'Assistant Craft Service': 'crew',
  'Assistant Decorator': 'designed by',
  'Assistant Dialogue Editor': 'with sound by',
  'Assistant Director': 'directed by',
  'Assistant Director Trainee': 'directed by',
  'Assistant Director of Photography': 'shot by',
  'Assistant Editor': 'edited by',
  'Assistant Electrician': 'lit by',
  'Assistant Extras Casting': 'produced by',
  'Assistant Foley Artist': 'with sound by',
  'Assistant Gaffer': 'lit by',
  'Assistant Grip': 'shot by',
  'Assistant Hairdresser': 'with costumes and makeup by',
  'Assistant Hairstylist': 'with costumes and makeup by',
  'Assistant Location Manager': 'produced by',
  'Assistant Makeup Artist': 'with costumes and makeup by',
  'Assistant Music Supervisor': 'with sound by',
  'Assistant Picture Car Coordinator': 'crew',
  'Assistant Picture Editor': 'edited by',
  'Assistant Production Coordinator': 'produced by',
  'Assistant Production Design': 'designed by',
  'Assistant Production Manager': 'produced by',
  'Assistant Property Master': 'designed by',
  'Assistant Script': 'crew',
  'Assistant Set Decoration': 'designed by',
  'Assistant Set Decoration Buyer': 'designed by',
  'Assistant Set Designer': 'designed by',
  'Assistant Set Dresser': 'designed by',
  'Assistant Set Propsman': 'designed by',
  'Assistant Sound Designer': 'with sound by',
  'Assistant Sound Editor': 'with sound by',
  'Assistant Sound Engineer': 'with sound by',
  'Assistant Unit Manager': 'produced by',
  'Assistant Vehicles Coordinator': 'crew',
  'Associate Choreographer': 'crew',
  'Associate Editor': 'edited by',
  'Associate Producer': 'produced by',
  'Atmos Editor': 'edited by',
  'Attorney': 'produced by',
  'Audio Post Coordinator': 'with sound by',
  'Author': 'written by',
  'BTS Footage': 'shot by',
  'BTS Photographer': 'shot by',
  'BTS Videographer': 'shot by',
  'Back-up Set Production Assistant': 'produced by',
  'Back-up Truck Production Assistant': 'produced by',
  'Background Casting Director': 'produced by',
  'Background Designer': 'designed by',
  'Base Camp Operator': 'crew',
  'Battle Motion Coordinator': 'with visual effects by',
  'Best Boy Electric': 'lit by',
  'Best Boy Electrician': 'lit by',
  'Best Boy Grip': 'shot by',
  'Best Boy Lighting Technician': 'lit by',
  'Book': 'written by',
  'Boom Operator': 'with sound by',
  'Broadcast Producer': 'produced by',
  'Business Affairs Coordinator': 'produced by',
  'CG Animator': 'with visual effects by',
  'CG Artist': 'with visual effects by',
  'CG Engineer': 'with visual effects by',
  'CG Painter': 'with visual effects by',
  'CG Supervisor': 'crew',
  'CGI Director': 'with visual effects by',
  'CGI Supervisor': 'crew',
  'Cableman': 'crew',
  'Cameo': 'starring',
  'Camera': 'shot by',
  'Camera Car': 'shot by',
  'Camera Department Manager': 'shot by',
  'Camera Department Production Assistant': 'shot by',
  'Camera Intern': 'shot by',
  'Camera Loader': 'shot by',
  'Camera Operator': 'shot by',
  'Camera Production Assistant': 'shot by',
  'Camera Supervisor': 'shot by',
  'Camera Technician': 'shot by',
  'Camera Trainee': 'shot by',
  'Camera Truck': 'shot by',
  'Captain Driver': 'crew',
  'Carpenter': 'crew',
  'Cast Driver': 'crew',
  'Casting': 'produced by',
  'Casting Assistant': 'produced by',
  'Casting Associate': 'produced by',
  'Casting Consultant': 'produced by',
  'Casting Coordinator': 'produced by',
  'Casting Director': 'produced by',
  'Casting Producer': 'produced by',
  'Casting Researcher': 'produced by',
  'Catering': 'crew',
  'Catering Head Chef': 'crew',
  'Chaperone': 'crew',
  'Chaperone Tutor': 'crew',
  'Character Designer': 'with visual effects by',
  'Character Modelling Supervisor': 'with visual effects by',
  'Character Technical Supervisor': 'produced by',
  'Characters': 'written by',
  'Charge Scenic Artist': 'crew',
  'Chef': 'crew',
  'Chief Lighting Technician': 'lit by',
  'Chief Technician / Stop-Motion Expert': 'with visual effects by',
  'Child Wrangler': 'crew',
  'Choreographer': 'choreographed by',
  'Cinematography': 'crew',
  'Clapper Loader': 'shot by',
  'Clearances Consultant': 'crew',
  'Clearances Coordinator': 'crew',
  'Cloth Setup': 'with visual effects by',
  'Co-Art Director': 'designed by',
  'Co-Costume Designer': 'with costumes and makeup by',
  'Co-Director': 'directed by',
  'Co-Editor': 'edited by',
  'Co-Executive Producer': 'produced by',
  'Co-Producer': 'produced by',
  'Co-Writer': 'written by',
  'Color Assistant': 'edited by',
  'Color Designer': 'with visual effects by',
  'Color Grading': 'edited by',
  'Color Timer': 'edited by',
  'Colorist': 'edited by',
  'Comic Book': 'written by',
  'Commissioning Editor': 'crew',
  'Compositing Artist': 'with visual effects by',
  'Compositing Lead': 'with visual effects by',
  'Compositing Supervisor': 'with visual effects by',
  'Compositor': 'crew',
  'Concept Artist': 'designed by',
  'Conceptual Design': 'designed by',
  'Conceptual Illustrator': 'designed by',
  'Conductor': 'with sound by',
  'Construction Buyer': 'designed by',
  'Construction Coordinator': 'designed by',
  'Construction Foreman': 'designed by',
  'Construction Grip': 'designed by',
  'Construction Manager': 'designed by',
  'Consulting Accountant': 'produced by',
  'Consulting Editor': 'edited by',
  'Consulting Producer': 'produced by',
  'Contact Lens Designer': 'with costumes and makeup by',
  'Contact Lens Painter': 'with costumes and makeup by',
  'Contact Lens Technician': 'with costumes and makeup by',
  'Continuity': 'directed by',
  'Contract Manager': 'produced by',
  'Controller': 'produced by',
  'Coordinating Producer': 'produced by',
  'Costume & Make-Up': 'with costumes and makeup by',
  'Costume Assistant': 'with costumes and makeup by',
  'Costume Consultant': 'with costumes and makeup by',
  'Costume Coordinator': 'with costumes and makeup by',
  'Costume Design': 'with costumes and makeup by',
  'Costume Designer': 'with costumes and makeup by',
  'Costume Illustrator': 'with costumes and makeup by',
  'Costume Mistress': 'with costumes and makeup by',
  'Costume Set Supervisor': 'with costumes and makeup by',
  'Costume Standby': 'with costumes and makeup by',
  'Costume Supervisor': 'with costumes and makeup by',
  'Costumer': 'with costumes and makeup by',
  'Craft Service': 'crew',
  'Creative Consultant': 'crew',
  'Creative Director': 'designed by',
  'Creative Producer': 'written by',
  'Creator': 'created by',
  'Creature Design': 'with visual effects by',
  'Creature Effects Technical Director': 'with visual effects by',
  'Creature Technical Director': 'with visual effects by',
  'Crew': 'crew',
  'Crowd Assistant Director': 'directed by',
  'Cyber Scanning Supervisor': 'with visual effects by',
  'Dailies Manager': 'edited by',
  'Dailies Operator': 'edited by',
  'Dailies Technician': 'edited by',
  'Daily Electrics': 'lit by',
  'Daily Grip': 'designed by',
  'Daily Makeup & Hair': 'with costumes and makeup by',
  'Daily Wardrobe': 'with costumes and makeup by',
  'Data Management Technician': 'produced by',
  'Data Wrangler': 'shot by',
  'Decorator': 'designed by',
  'Delegated Producer': 'produced by',
  'Department Administrator': 'crew',
  'Development Manager': 'produced by',
  'Development Producer': 'produced by',
  'Dialect Coach': 'crew',
  'Dialogue': 'written by',
  'Dialogue Coach': 'crew',
  'Dialogue Editor': 'with sound by',
  'Digital Color Timer': 'edited by',
  'Digital Colorist': 'edited by',
  'Digital Compositor': 'with visual effects by',
  'Digital Conform Editor': 'edited by',
  'Digital Effects Producer': 'with visual effects by',
  'Digital Effects Supervisor': 'crew',
  'Digital Film Recording': 'with visual effects by',
  'Digital Foley Artist': 'with sound by',
  'Digital Imaging Technician': 'shot by',
  'Digital Intermediate': 'edited by',
  'Digital Intermediate Assistant': 'edited by',
  'Digital Intermediate Colorist': 'edited by',
  'Digital Intermediate Data Wrangler': 'edited by',
  'Digital Intermediate Editor': 'edited by',
  'Digital Intermediate Producer': 'edited by',
  'Digital Producer': 'crew',
  'Digital Storyboarding': 'designed by',
  'Digital Supervisor': 'crew',
  'Directing': 'directed by',
  'Directing Lighting Artist': 'lit by',
  'Director': 'directed by',
  'Director of Communications': 'crew',
  'Director of Operations': 'produced by',
  'Director of Photography': 'shot by',
  'Director of Previsualization': 'with visual effects by',
  'Documentation & Support': 'crew',
  'Dolby Consultant': 'with sound by',
  'Dolly Grip': 'shot by',
  'Dramaturgy': 'crew',
  'Draughtsman': 'designed by',
  'Dresser': 'with costumes and makeup by',
  'Dressing Prop': 'designed by',
  'Driver': 'crew',
  'Drone Cinematographer': 'shot by',
  'Drone Operator': 'crew',
  'Drone Pilot': 'shot by',
  'EPK Editor': 'edited by',
  'Editing': 'edited by',
  'Editor': 'edited by',
  'Editorial Consultant': 'edited by',
  'Editorial Coordinator': 'edited by',
  'Editorial Manager': 'edited by',
  'Editorial Production Assistant': 'edited by',
  'Editorial Services': 'edited by',
  'Editorial Staff': 'crew',
  'Effects Supervisor': 'with visual effects by',
  'Electrician': 'lit by',
  'Epk Camera Operator': 'shot by',
  'Epk Director': 'shot by',
  'Epk Producer': 'shot by',
  'Executive Assistant': 'produced by',
  'Executive Co-Producer': 'produced by',
  'Executive Consultant': 'produced by',
  'Executive In Charge Of Post Production': 'produced by',
  'Executive In Charge Of Production': 'produced by',
  'Executive Music Producer': 'crew',
  'Executive Producer': 'produced by',
  'Executive Producer\'s Assistant': 'produced by',
  'Executive Story Editor': 'written by',
  'Executive Visual Effects Producer': 'crew',
  'Executive in Charge of Finance': 'crew',
  'Extras Casting': 'produced by',
  'Extras Casting Assistant': 'produced by',
  'Extras Casting Coordinator': 'produced by',
  'Extras Dresser': 'with costumes and makeup by',
  'Extras Makeup Artist': 'with costumes and makeup by',
  'Facial Setup Artist': 'with costumes and makeup by',
  'Feature Finishing Producer': 'produced by',
  'Field Director': 'directed by',
  'Fight Choreographer': 'crew',
  'File Footage': 'crew',
  'Film Processor': 'crew',
  'Finance': 'produced by',
  'Finishing Producer': 'produced by',
  'First Assistant "A" Camera': 'shot by',
  'First Assistant "B" Camera': 'shot by',
  'First Assistant "C" Camera': 'shot by',
  'First Assistant "D" Camera': 'shot by',
  'First Assistant Accountant': 'produced by',
  'First Assistant Art Direction': 'designed by',
  'First Assistant Camera': 'shot by',
  'First Assistant Director': 'directed by',
  'First Assistant Director (Prep)': 'directed by',
  'First Assistant Director Trainee': 'directed by',
  'First Assistant Editor': 'edited by',
  'First Assistant Hairstylist': 'with costumes and makeup by',
  'First Assistant Makeup Artist': 'with costumes and makeup by',
  'First Assistant Picture Editor': 'edited by',
  'First Assistant Production Coordinator': 'produced by',
  'First Assistant Property Master': 'designed by',
  'First Assistant Sound Editor': 'with sound by',
  'First Company Grip': 'shot by',
  'Fix Animator': 'with visual effects by',
  'Floor Runner': 'crew',
  'Focus Puller': 'shot by',
  'Foley': 'with sound by',
  'Foley Artist': 'with sound by',
  'Foley Editor': 'with sound by',
  'Foley Mixer': 'with sound by',
  'Foley Recording Engineer': 'with sound by',
  'Foley Recordist': 'with sound by',
  'Foley Supervisor': 'with sound by',
  'Gaffer': 'lit by',
  'General Manager': 'produced by',
  'Generalist': 'with visual effects by',
  'Generator Operator': 'crew',
  'Genetator Operator': 'lit by',
  'Graphic Designer': 'designed by',
  'Graphic Novel': 'written by',
  'Graphic Novel Illustrator': 'crew',
  'Greensman': 'designed by',
  'Grip': 'shot by',
  'Grip Production Assistant': 'produced by',
  'Gun Wrangler': 'designed by',
  'Hair Assistant': 'with costumes and makeup by',
  'Hair Department Head': 'with costumes and makeup by',
  'Hair Designer': 'with costumes and makeup by',
  'Hair Setup': 'with costumes and makeup by',
  'Hair Supervisor': 'with costumes and makeup by',
  'Hairdresser': 'with costumes and makeup by',
  'Hairstylist': 'with costumes and makeup by',
  'Head Carpenter': 'designed by',
  'Head Decorator': 'designed by',
  'Head Designer': 'designed by',
  'Head Driver': 'crew',
  'Head Greensman': 'designed by',
  'Head of Animation': 'with visual effects by',
  'Head of Layout': 'shot by',
  'Head of Production': 'produced by',
  'Head of Programming': 'produced by',
  'Head of Research': 'produced by',
  'Head of Story': 'written by',
  'Health and Safety': 'crew',
  'Helicopter Camera': 'shot by',
  'Helping Hand': 'designed by',
  'Human Resources': 'produced by',
  'I/O Manager': 'with visual effects by',
  'I/O Supervisor': 'with visual effects by',
  'Idea': 'written by',
  'Imaging Science': 'with visual effects by',
  'In Memory Of': 'crew',
  'Information Systems Manager': 'crew',
  'Insert Unit Director': 'directed by',
  'Insert Unit First Assistant Director': 'directed by',
  'Insert Unit Location Manager': 'produced by',
  'Interactive Manager': 'crew',
  'Interior Designer': 'designed by',
  'Intern': 'crew',
  'Jimmy Jib Operator': 'shot by',
  'Joint ADR Mixer': 'with sound by',
  'Junior Story Editor': 'written by',
  'Key Accountant': 'produced by',
  'Key Animation': 'with visual effects by',
  'Key Art Production Assistant': 'produced by',
  'Key Carpenter': 'designed by',
  'Key Construction Grip': 'designed by',
  'Key Costumer': 'with costumes and makeup by',
  'Key Dresser': 'with costumes and makeup by',
  'Key Grip': 'shot by',
  'Key Grip Production Assistant': 'produced by',
  'Key Hair Stylist': 'with costumes and makeup by',
  'Key Hairdresser': 'with costumes and makeup by',
  'Key Makeup Artist': 'with costumes and makeup by',
  'Key Production Assistant': 'produced by',
  'Key Rigging Grip': 'lit by',
  'Key Scenic Artist': 'crew',
  'Key Set Costumer': 'with costumes and makeup by',
  'Key Set Painter': 'designed by',
  'Key Set Production Assistant': 'produced by',
  'Key Special Effects': 'crew',
  'Keyboard Programmer': 'with sound by',
  'Layout': 'directed by',
  'Layout Supervisor': 'with visual effects by',
  'Lead Animator': 'with visual effects by',
  'Lead Character Designer': 'with visual effects by',
  'Lead Costumer': 'with costumes and makeup by',
  'Lead Creature Designer': 'with visual effects by',
  'Lead Editor': 'edited by',
  'Lead Painter': 'designed by',
  'Lead Set Dresser': 'designed by',
  'Leadman': 'designed by',
  'Legal Services': 'crew',
  'Libra Head Technician': 'shot by',
  'Lighting': 'lit by',
  'Lighting Artist': 'lit by',
  'Lighting Camera': 'crew',
  'Lighting Coordinator': 'lit by',
  'Lighting Design': 'lit by',
  'Lighting Director': 'lit by',
  'Lighting Manager': 'lit by',
  'Lighting Production Assistant': 'lit by',
  'Lighting Programmer': 'lit by',
  'Lighting Supervisor': 'lit by',
  'Lighting Technician': 'lit by',
  'Line Producer': 'produced by',
  'Loader': 'crew',
  'Local Casting': 'produced by',
  'Locale Casting Director': 'produced by',
  'Location Assistant': 'produced by',
  'Location Casting': 'produced by',
  'Location Coordinator': 'produced by',
  'Location Manager': 'produced by',
  'Location Production Assistant': 'produced by',
  'Location Scout': 'designed by',
  'Location Sound Assistant': 'with sound by',
  'Location Sound Mixer': 'with sound by',
  'Location Sound Recordist': 'with sound by',
  'Logistics Coordinator': 'crew',
  'Loop Group Coordinator': 'with sound by',
  'Lyricist': 'written by',
  'Machinist': 'crew',
  'Main Title Designer': 'designed by',
  'Main Title Theme Composer': 'with sound by',
  'Makeup & Hair': 'with costumes and makeup by',
  'Makeup & Hair Assistant': 'with costumes and makeup by',
  'Makeup Artist': 'with costumes and makeup by',
  'Makeup Department Head': 'with costumes and makeup by',
  'Makeup Designer': 'with costumes and makeup by',
  'Makeup Effects': 'crew',
  'Makeup Effects Designer': 'with costumes and makeup by',
  'Makeup Supervisor': 'with costumes and makeup by',
  'Makeup Trainee': 'with costumes and makeup by',
  'Manager of Operations': 'crew',
  'Marine Coordinator': 'crew',
  'Marine Pilot': 'crew',
  'Martial Arts Choreographer': 'crew',
  'Master Lighting Artist': 'lit by',
  'Master at Arms': 'crew',
  'Matchmove Supervisor': 'with visual effects by',
  'Matte Painter': 'with visual effects by',
  'Mechanical & Creature Designer': 'with visual effects by',
  'Mechanical Designer': 'with visual effects by',
  'Medical Consultant': 'crew',
  'Military Consultant': 'crew',
  'Mix Technician': 'crew',
  'Mixing Engineer': 'crew',
  'Modeling': 'with visual effects by',
  'Modelling Supervisor': 'with visual effects by',
  'Motion Actor': 'crew',
  'Motion Capture Artist': 'crew',
  'Music': 'with sound by',
  'Music Arranger': 'with sound by',
  'Music Co-Supervisor': 'with sound by',
  'Music Consultant': 'with sound by',
  'Music Coordinator': 'with sound by',
  'Music Director': 'with sound by',
  'Music Editor': 'with sound by',
  'Music Producer': 'with sound by',
  'Music Programmer': 'with sound by',
  'Music Score Producer': 'with sound by',
  'Music Sound Design and Processing': 'with sound by',
  'Music Supervision Assistant': 'with sound by',
  'Music Supervisor': 'with sound by',
  'Musical': 'written by',
  'Musical Casting': 'produced by',
  'Musician': 'with sound by',
  'Negative Cutter': 'edited by',
  'Novel': 'written by',
  'O.B. Lighting': 'lit by',
  'O.B. Sound': 'with sound by',
  'On Set Computer Graphics': 'designed by',
  'On Set Dresser': 'with costumes and makeup by',
  'On Set Key Props': 'designed by',
  'On Set Props': 'designed by',
  'Online Editor': 'edited by',
  'Opening Title Sequence': 'designed by',
  'Opening/Ending Animation': 'with visual effects by',
  'Opera': 'written by',
  'Orchestrator': 'with sound by',
  'Original Casting': 'produced by',
  'Original Concept': 'written by',
  'Original Film Writer': 'written by',
  'Original Music Composer': 'with sound by',
  'Original Series Creator': 'written by',
  'Original Series Design': 'designed by',
  'Original Story': 'written by',
  'Other': 'edited by',
  'Paint Coordinator': 'designed by',
  'Painter': 'designed by',
  'Payroll Accountant': 'produced by',
  'Petty Cash Buyer': 'designed by',
  'Phantom Operator': 'shot by',
  'Photo Retouching': 'with visual effects by',
  'Photoscience Manager': 'crew',
  'Picture Car Coordinator': 'crew',
  'Pilot': 'crew',
  'Pipeline Technical Director': 'with visual effects by',
  'Playback Coordinator': 'crew',
  'Playback Singer': 'with sound by',
  'Poem': 'crew',
  'Police Consultant': 'crew',
  'Post Coordinator': 'produced by',
  'Post Producer': 'produced by',
  'Post Production Accountant': 'produced by',
  'Post Production Assistant': 'crew',
  'Post Production Consulting': 'crew',
  'Post Production Coordinator': 'produced by',
  'Post Production Producer': 'produced by',
  'Post Production Scripts': 'crew',
  'Post Production Supervisor': 'crew',
  'Post Production Technical Engineer': 'produced by',
  'Post-Production Manager': 'crew',
  'Pre-Visualization Coordinator': 'with visual effects by',
  'Pre-Visualization Supervisor': 'with visual effects by',
  'Presenter': 'presented by',
  'Principal Costumer': 'with costumes and makeup by',
  'Producer': 'produced by',
  'Producer\'s Assistant': 'produced by',
  'Production': 'produced by',
  'Production Accountant': 'produced by',
  'Production Artist': 'crew',
  'Production Assistant': 'produced by',
  'Production Consultant': 'produced by',
  'Production Controller': 'crew',
  'Production Coordinator': 'produced by',
  'Production Design': 'designed by',
  'Production Designer': 'produced by',
  'Production Director': 'produced by',
  'Production Driver': 'produced by',
  'Production Executive': 'produced by',
  'Production Illustrator': 'designed by',
  'Production Intern': 'crew',
  'Production Manager': 'produced by',
  'Production Office Assistant': 'crew',
  'Production Office Coordinator': 'produced by',
  'Production Runner': 'produced by',
  'Production Secretary': 'produced by',
  'Production Sound Mixer': 'with sound by',
  'Production Supervisor': 'produced by',
  'Production Trainee': 'produced by',
  'Project Manager': 'edited by',
  'Projection': 'crew',
  'Prop Designer': 'designed by',
  'Prop Maker': 'crew',
  'Property Builder': 'designed by',
  'Property Buyer': 'designed by',
  'Property Graphic Designer': 'designed by',
  'Property Master': 'designed by',
  'Propmaker': 'crew',
  'Props': 'designed by',
  'Prosthetic Designer': 'with costumes and makeup by',
  'Prosthetic Makeup Artist': 'with costumes and makeup by',
  'Prosthetic Supervisor': 'with costumes and makeup by',
  'Prosthetics': 'with costumes and makeup by',
  'Prosthetics Painter': 'with costumes and makeup by',
  'Prosthetics Sculptor': 'with costumes and makeup by',
  'Public Relations': 'crew',
  'Publicist': 'produced by',
  'Pyrotechnic Supervisor': 'with visual effects by',
  'Pyrotechnician': 'crew',
  'Quality Control Supervisor': 'crew',
  'Radio Play': 'crew',
  'Receptionist': 'crew',
  'Recording Supervision': 'with sound by',
  'Red Technician': 'shot by',
  'Research Assistant': 'produced by',
  'Researcher': 'produced by',
  'Rigging Gaffer': 'lit by',
  'Rigging Grip': 'lit by',
  'Rigging Supervisor': 'lit by',
  'Roto Supervisor': 'with visual effects by',
  'Rotoscoping Artist': 'with visual effects by',
  'Runner Art Department': 'designed by',
  'Russian Arm Operator': 'shot by',
  'Scenario Writer': 'written by',
  'Scenic Artist': 'crew',
  'Schedule Coordinator': 'crew',
  'Scientific Consultant': 'crew',
  'Score Engineer': 'crew',
  'Scoring Mixer': 'with sound by',
  'Screenplay': 'written by',
  'Screenstory': 'written by',
  'Script': 'crew',
  'Script Consultant': 'written by',
  'Script Coordinator': 'directed by',
  'Script Editor': 'written by',
  'Script Researcher': 'produced by',
  'Script Supervisor': 'directed by',
  'Sculptor': 'designed by',
  'Seamstress': 'with costumes and makeup by',
  'Second Assistant "A" Camera': 'shot by',
  'Second Assistant "B" Camera': 'shot by',
  'Second Assistant "C" Camera': 'shot by',
  'Second Assistant "D" Camera': 'shot by',
  'Second Assistant Accountant': 'produced by',
  'Second Assistant Art Director': 'designed by',
  'Second Assistant Camera': 'shot by',
  'Second Assistant Director': 'directed by',
  'Second Assistant Director Trainee': 'directed by',
  'Second Assistant Production Coordinator': 'produced by',
  'Second Assistant Sound': 'with sound by',
  'Second Assistant Unit Manager': 'produced by',
  'Second Company Grip': 'shot by',
  'Second Film Editor': 'crew',
  'Second Second Assistant Director': 'directed by',
  'Second Unit': 'crew',
  'Second Unit Cinematographer': 'crew',
  'Second Unit Director': 'directed by',
  'Second Unit Director of Photography': 'shot by',
  'Second Unit First Assistant Director': 'directed by',
  'Second Unit Location Manager': 'produced by',
  'Security': 'crew',
  'Security Coordinator': 'crew',
  'Senior Animator': 'with visual effects by',
  'Senior Colorist': 'edited by',
  'Senior Digital Intermediate Colorist': 'edited by',
  'Senior Executive Consultant': 'produced by',
  'Senior Generalist': 'with visual effects by',
  'Senior Modeller': 'with visual effects by',
  'Senior Story Editor': 'written by',
  'Senior Visual Effects Supervisor': 'with visual effects by',
  'Sequence Artist': 'crew',
  'Sequence Lead': 'crew',
  'Sequence Supervisor': 'crew',
  'Series Composition': 'written by',
  'Series Director': 'directed by',
  'Series Publicist': 'crew',
  'Series Writer': 'crew',
  'Set Buyer': 'designed by',
  'Set Costumer': 'with costumes and makeup by',
  'Set Decorating Coordinator': 'designed by',
  'Set Decoration': 'designed by',
  'Set Decoration Buyer': 'designed by',
  'Set Designer': 'designed by',
  'Set Dresser': 'designed by',
  'Set Dressing Artist': 'with costumes and makeup by',
  'Set Dressing Buyer': 'designed by',
  'Set Dressing Manager': 'with costumes and makeup by',
  'Set Dressing Production Assistant': 'with costumes and makeup by',
  'Set Dressing Supervisor': 'with costumes and makeup by',
  'Set Medic': 'crew',
  'Set Painter': 'designed by',
  'Set Photographer': 'shot by',
  'Set Production Assistant': 'crew',
  'Set Production Intern': 'crew',
  'Set Propsman': 'designed by',
  'Set Runner': 'crew',
  'Set Supervisor': 'designed by',
  'Sets & Props Artist': 'crew',
  'Sets & Props Supervisor': 'crew',
  'Settings': 'designed by',
  'Shading': 'with visual effects by',
  'Shoe Design': 'with costumes and makeup by',
  'Shop Electric': 'designed by',
  'Short Story': 'written by',
  'Sign Painter': 'designed by',
  'Simulation & Effects Artist': 'with visual effects by',
  'Simulation & Effects Production Assistant': 'with visual effects by',
  'Smoke Artist': 'with visual effects by',
  'Software Engineer': 'crew',
  'Software Team Lead': 'crew',
  'Songs': 'with sound by',
  'Sound': 'with sound by',
  'Sound Assistant': 'with sound by',
  'Sound Design Assistant': 'crew',
  'Sound Designer': 'with sound by',
  'Sound Director': 'with sound by',
  'Sound Editor': 'with sound by',
  'Sound Effects': 'with sound by',
  'Sound Effects Designer': 'with sound by',
  'Sound Effects Editor': 'with sound by',
  'Sound Engineer': 'with sound by',
  'Sound Mix Technician': 'with sound by',
  'Sound Mixer': 'with sound by',
  'Sound Montage Associate': 'with sound by',
  'Sound Post Production Coordinator': 'with sound by',
  'Sound Post Supervisor': 'with sound by',
  'Sound Re-Recording Assistant': 'with sound by',
  'Sound Re-Recording Mixer': 'with sound by',
  'Sound Recordist': 'with sound by',
  'Sound Supervisor': 'with sound by',
  'Sound Technical Supervisor': 'with sound by',
  'Special Effects': 'crew',
  'Special Effects Assistant': 'crew',
  'Special Effects Best Boy': 'crew',
  'Special Effects Coordinator': 'crew',
  'Special Effects Key Makeup Artist': 'with costumes and makeup by',
  'Special Effects Makeup Artist': 'with costumes and makeup by',
  'Special Effects Manager': 'crew',
  'Special Effects Supervisor': 'with visual effects by',
  'Special Effects Technician': 'crew',
  'Special Guest': 'starring',
  'Special Guest Director': 'directed by',
  'Special Props': 'designed by',
  'Special Sound Effects': 'crew',
  'Specialized Driver': 'crew',
  'Sponsorship Coordinator': 'crew',
  'Sponsorship Director': 'crew',
  'Staff Writer': 'written by',
  'Stage Director': 'directed by',
  'Stand In': 'crew',
  'Standby Art Director': 'designed by',
  'Standby Carpenter': 'designed by',
  'Standby Painter': 'designed by',
  'Standby Property Master': 'designed by',
  'Standby Rigger': 'lit by',
  'Steadicam Operator': 'shot by',
  'Steadycam': 'crew',
  'Stereoscopic Coordinator': 'with visual effects by',
  'Stereoscopic Editor': 'edited by',
  'Stereoscopic Supervisor': 'with visual effects by',
  'Stereoscopic Technical Director': 'with visual effects by',
  'Still Photographer': 'shot by',
  'Story': 'written by',
  'Story Artist': 'written by',
  'Story Consultant': 'written by',
  'Story Coordinator': 'written by',
  'Story Developer': 'written by',
  'Story Editor': 'written by',
  'Story Manager': 'written by',
  'Story Supervisor': 'written by',
  'Storyboard': 'written by',
  'Storyboard Artist': 'designed by',
  'Storyboard Assistant': 'designed by',
  'Storyboard Designer': 'designed by',
  'Street Casting': 'produced by',
  'Studio Teacher': 'crew',
  'Stunt Coordinator': 'crew',
  'Stunt Double': 'with stunts by',
  'Stunt Driver': 'crew',
  'Stunts': 'with stunts by',
  'Supervising ADR Editor': 'with sound by',
  'Supervising Animation Director': 'with visual effects by',
  'Supervising Animator': 'crew',
  'Supervising Armorer': 'crew',
  'Supervising Art Director': 'designed by',
  'Supervising Carpenter': 'designed by',
  'Supervising Dialogue Editor': 'with sound by',
  'Supervising Editor': 'edited by',
  'Supervising Film Editor': 'edited by',
  'Supervising Music Editor': 'with sound by',
  'Supervising Producer': 'produced by',
  'Supervising Sound Editor': 'with sound by',
  'Supervising Sound Effects Editor': 'with sound by',
  'Supervising Technical Director': 'crew',
  'Supervisor of Production Resources': 'crew',
  'Swing': 'designed by',
  'Systems Administrators & Support': 'crew',
  'Tailor': 'with costumes and makeup by',
  'Tattoo Designer': 'with costumes and makeup by',
  'Tattooist': 'crew',
  'Technical Advisor': 'crew',
  'Technical Supervisor': 'crew',
  'Techno Crane Operator': 'crew',
  'Telecine Colorist': 'crew',
  'Teleplay': 'written by',
  'Temp Music Editor': 'crew',
  'Temp Sound Editor': 'crew',
  'Textile Artist': 'designed by',
  'Thanks': 'crew',
  'Theatre Play': 'written by',
  'Theme Song Performance': 'with sound by',
  'Third Assistant "A" Camera': 'shot by',
  'Third Assistant "B" Camera': 'shot by',
  'Third Assistant "C" Camera': 'shot by',
  'Third Assistant "D" Camera': 'shot by',
  'Third Assistant Camera': 'shot by',
  'Third Assistant Director': 'directed by',
  'Title Designer': 'designed by',
  'Title Graphics': 'crew',
  'Title Illustration': 'designed by',
  'Trainee Production Coordinator': 'produced by',
  'Transcriptions': 'crew',
  'Translator': 'crew',
  'Transportation Captain': 'crew',
  'Transportation Co-Captain': 'crew',
  'Transportation Coordinator': 'crew',
  'Travel Coordinator': 'produced by',
  'Treatment': 'crew',
  'Truck Costumer': 'with costumes and makeup by',
  'Truck Production Assistant': 'produced by',
  'Truck Supervisor': 'with costumes and makeup by',
  'Ultimate Arm Operator': 'shot by',
  'Underwater Camera': 'shot by',
  'Underwater Director of Photography': 'shot by',
  'Underwater Epk Photographer': 'shot by',
  'Underwater Gaffer': 'lit by',
  'Underwater Stills Photographer': 'shot by',
  'Unit Manager': 'produced by',
  'Unit Medic': 'crew',
  'Unit Production Manager': 'produced by',
  'Unit Publicist': 'crew',
  'Unit Swing': 'produced by',
  'Utility Sound': 'with sound by',
  'Utility Stunts': 'crew',
  'VFX Artist': 'with visual effects by',
  'VFX Director of Photography': 'with visual effects by',
  'VFX Editor': 'with visual effects by',
  'VFX Lighting Artist': 'with visual effects by',
  'VFX Production Coordinator': 'with visual effects by',
  'VFX Supervisor': 'with visual effects by',
  'Vehicles Coordinator': 'crew',
  'Vehicles Wrangler': 'crew',
  'Video Assist Operator': 'crew',
  'Video Game': 'crew',
  'Video Report': 'shot by',
  'Videojournalist': 'shot by',
  'Visual Development': 'with visual effects by',
  'Visual Effects': 'with visual effects by',
  'Visual Effects Art Director': 'crew',
  'Visual Effects Assistant Editor': 'with visual effects by',
  'Visual Effects Camera': 'with visual effects by',
  'Visual Effects Compositor': 'with visual effects by',
  'Visual Effects Coordinator': 'with visual effects by',
  'Visual Effects Design Consultant': 'crew',
  'Visual Effects Designer': 'with visual effects by',
  'Visual Effects Director': 'with visual effects by',
  'Visual Effects Editor': 'crew',
  'Visual Effects Lineup': 'with visual effects by',
  'Visual Effects Producer': 'with visual effects by',
  'Visual Effects Production Assistant': 'with visual effects by',
  'Visual Effects Production Manager': 'with visual effects by',
  'Visual Effects Supervisor': 'with visual effects by',
  'Visual Effects Technical Director': 'with visual effects by',
  'Vocal Coach': 'with sound by',
  'Vocals': 'with sound by',
  'Voice': 'starring',
  'Wardrobe Assistant': 'with costumes and makeup by',
  'Wardrobe Coordinator': 'with costumes and makeup by',
  'Wardrobe Designer': 'with costumes and makeup by',
  'Wardrobe Intern': 'with costumes and makeup by',
  'Wardrobe Master': 'with costumes and makeup by',
  'Wardrobe Specialized Technician': 'with costumes and makeup by',
  'Wardrobe Supervisor': 'with costumes and makeup by',
  'Weapons Master': 'crew',
  'Weapons Wrangler': 'crew',
  'Web Designer': 'designed by',
  'Wig Designer': 'with costumes and makeup by',
  'Wigmaker': 'with costumes and makeup by',
  'Writer': 'written by',
  'Writers\' Assistant': 'written by',
  'Writers\' Production': 'written by',
  'Writing': 'written by',
};

function headingForPhrase(personName: string, phrase: string): string {
  if (phrase === 'starring') {
    return `Titles starring ${personName}`;
  }
  if (phrase === 'crew') {
    return `Titles with ${personName} on the crew`;
  }
  return `Titles ${phrase} ${personName}`;
}

/** Section title for the filmography profession filter. */
export function filmographyHeading(
  personName: string,
  profession: string,
): string {
  const key = profession.trim();
  const phrase = PHRASE_BY_PROFESSION[key];
  if (phrase) {
    return headingForPhrase(personName, phrase);
  }
  if (!key) {
    return `Titles with ${personName}`;
  }
  return `${key} credits for ${personName}`;
}
